CREATE TABLE "frame_samples" (
    id INTEGER PRIMARY KEY,
    "sclkCoarse" INTEGER,
    "sclkFine" INTEGER,
    "ert" TEXT,
    "ertExplicitlySet" NUMERIC,
    "ertStr" TEXT,
    "ertStrExplicitlySet" NUMERIC,
    "ertEpochMs" NUMERIC NOT NULL,
    "scet" TEXT,
    "pathId" INTEGER,
    "vcid" INTEGER,
    "vcfc" INTEGER,
    "mcfc" INTEGER,
    "tkSclkCoarse" INTEGER,
    "tkSclkFine" INTEGER,
    "tkVcid" INTEGER,
    "tkVcfc" INTEGER,
    "tkDataRateBps" REAL,
    "tkRfEncoding" TEXT,
    "tkIsValid" TEXT,
    "suppVcid" INTEGER,
    "suppVcfc" INTEGER,
    "suppMcfc" INTEGER,
    "suppErt" TEXT,
    "suppErtExplicitlySet" NUMERIC,
    "suppErtStr" TEXT,
    "suppErtStrExplicitlySet" NUMERIC,
    "frameSizeBits" INTEGER
);