/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "mmtc"
include(":mmtc-core")
include(":mmtc-plugin-ampcs")
include(":mmtc-output-plugin-sdk")
include(":mmtc-tlm-source-plugin-sdk")
include(":mmtc-webapp")
include(":mmtc-webapp-ui")
include(":jnispice")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library("commons-csv", "org.apache.commons:commons-csv:1.14.0")
            library("commons-lang3", "org.apache.commons:commons-lang3:3.18.0")
            library("commons-cli", "commons-cli:commons-cli:1.9.0")
            library("commons-io", "commons-io:commons-io:2.19.0")

            library("log4j-api", "org.apache.logging.log4j:log4j-api:2.25.1")
            library("log4j-core", "org.apache.logging.log4j:log4j-core:2.25.1")
            library("log4j-jcl", "org.apache.logging.log4j:log4j-jcl:2.25.1")
            library("log4j-slf4j", "org.apache.logging.log4j:log4j-slf4j2-impl:2.25.1")
        }

        create("testlibs") {
            library("junit-jupiter-api", "org.junit.jupiter:junit-jupiter-api:5.13.4")
            library("junit-jupiter-params", "org.junit.jupiter:junit-jupiter-params:5.13.4")
            library("junit-jupiter-engine", "org.junit.jupiter:junit-jupiter-engine:5.13.4")
            library("junit-platform-launcher", "org.junit.platform:junit-platform-launcher:1.13.4")
            library("mockito-inline", "org.mockito:mockito-inline:4.11.0")
        }
    }
}