package edu.jhuapl.sd.sig.mmtc.webapp.auth;

import edu.jhuapl.sd.sig.mmtc.webapp.config.MmtcWebAppConfig;
import io.javalin.http.Context;
import io.javalin.http.HttpResponseException;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

public class AutoGenBasicHttpAuthorizationService implements AuthorizationService {
    private static final String USERNAME = "mmtc";
    private static final String AUTH_EXPIRATION = "auth-expiration";

    private final String password;
    private final MmtcWebAppConfig config;

    public AutoGenBasicHttpAuthorizationService(MmtcWebAppConfig config) {
        this.config = config;
        password = UUID.randomUUID().toString();
        System.out.println("Please use these autogenerated auth credentials to access the application:");
        System.out.println("\t username: " + USERNAME);
        System.out.println("\t password: " + password);
    }

    @Override
    public boolean ensureAuthorized(Context ctx) {
        if (ctx.basicAuthCredentials() == null) {
            ctx.header("WWW-Authenticate", "Basic realm=\"MMTC\", charset=\"UTF-8\"");
            throw new HttpResponseException(401, "Please login");
        }

        if (ctx.sessionAttribute(AUTH_EXPIRATION) != null) {
            Instant authExpiration = ctx.sessionAttribute(AUTH_EXPIRATION);
            if (Instant.now().isAfter(authExpiration)) {
                ctx.consumeSessionAttribute(AUTH_EXPIRATION);
            } else {
                return true;
            }
        }

        final String submittedUsername = ctx.basicAuthCredentials().getUsername();
        final String submittedPassword = ctx.basicAuthCredentials().getPassword();

        if (submittedUsername.equals(USERNAME) && submittedPassword.equals(password)) {
            ctx.sessionAttribute(AUTH_EXPIRATION, Instant.now().plus(config.getAuthTimeoutHours(), ChronoUnit.HOURS));
            return true;
        } else {
            ctx.header("WWW-Authenticate", "Basic realm=\"MMTC\", charset=\"UTF-8\"");
            throw new HttpResponseException(401, "Please login");
        }
    }
}
