package edu.jhuapl.sd.sig.mmtc.webapp.auth;

import io.javalin.http.Context;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

public class AutoGenBasicHttpAuthorizationService implements AuthorizationService {
    private static final String USERNAME = "mmtc";
    private static final String AUTH_EXPIRATION = "auth-expiration";

    private final String password;

    public AutoGenBasicHttpAuthorizationService() {
        password = UUID.randomUUID().toString();
        System.out.println("Please use these autogenerated auth credentials to access the application:");
        System.out.println("\t username: " + USERNAME);
        System.out.println("\t password: " + password);
    }

    @Override
    public boolean isAuthorized(Context ctx) {
        if (ctx.sessionAttribute(AUTH_EXPIRATION) != null) {
            Instant authExpiration = ctx.sessionAttribute(AUTH_EXPIRATION);
            if (Instant.now().isAfter(authExpiration)) {
                ctx.consumeSessionAttribute(AUTH_EXPIRATION);
            } else {
                return true;
            }
        }

        final String submittedUsername = ctx.basicAuthCredentials().getUsername();
        final String submittedPassword = ctx.basicAuthCredentials().getPassword();

        if (submittedUsername.equals(USERNAME) && submittedPassword.equals(password)) {
            ctx.sessionAttribute(AUTH_EXPIRATION, Instant.now().plus(4, ChronoUnit.HOURS)); // todo make this configurable
            return true;
        } else {
            return false;
        }
    }
}
