package edu.jhuapl.sd.sig.mmtc.trending;

import edu.jhuapl.sd.sig.mmtc.cfg.app.MmtcConfig;
import edu.jhuapl.sd.sig.mmtc.correlation.TimeCorrelationAncillaryOperations;
import edu.jhuapl.sd.sig.mmtc.correlation.config.TimeCorrelationRunConfig;
import edu.jhuapl.sd.sig.mmtc.products.model.kernel.sclk.CorrelationTriplet;
import edu.jhuapl.sd.sig.mmtc.tlm.*;
import edu.jhuapl.sd.sig.mmtc.tlm.range.ErtRange;
import edu.jhuapl.sd.sig.mmtc.tlm.range.ScetRange;
import edu.jhuapl.sd.sig.mmtc.tlm.selection.TelemetrySelectionAndAdjustmentOptions;
import edu.jhuapl.sd.sig.mmtc.trending.config.TrendingConfig;
import edu.jhuapl.sd.sig.mmtc.products.model.kernel.sclk.SclkKernel;
import edu.jhuapl.sd.sig.mmtc.tlm.persistence.cache.OffsetDateTimeRange;
import edu.jhuapl.sd.sig.mmtc.trending.report.ReportWriter;
import edu.jhuapl.sd.sig.mmtc.trending.stats.ErrorTrendingMetrics;
import edu.jhuapl.sd.sig.mmtc.trending.stats.TrendingStats;
import edu.jhuapl.sd.sig.mmtc.util.Owlt;
import edu.jhuapl.sd.sig.mmtc.util.TimeConvert;
import edu.jhuapl.sd.sig.mmtc.util.TimeConvertException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Design:
 *
 * The HTML report should have two top-level sections (each separately enabled):
 * - Trending over past n days
 * - Trending since last correlation
 *
 * Each of these two sections has, for its own timeframe:
 * - Telemetry stats
 *   - Number of frame/packet samples: 92
 *   - Most recently processed telemetry received at: 2026-190T01:02:03.45 SCET (UTC)
 * - Up to two trending sections (one each for Ep(ms) Error and TDT(S) Error) (each separately enabled):
 *   - Plot
 *   - Latest value (and the related date of the input measurement(s))
 *   - Current rate, based on latest value, over the configured timespan
 *   - Configured error threshold
 *   - Time until threshold is violated based on rate
 *   - Date at which threshold might be violated
 * - Footer should report:
 *   - Generated by MMTC 1.7.0 (abcdef) on 2026-123T04:05:06.789 using SCLK kernel blah_123.tsc
 */
public class TrendingApp {
    private static final Logger logger = LogManager.getLogger();

    private final TrendingConfig config;
    // private final TrendingContext ctx;
    private final OffsetDateTime appRunTime;

    // This is the SCLK modulus (i.e., fine time ticks per second) related to FrameSample.tkSclkFine.
    // It is used to compute TF Offset for use in clock change rate calculations.
    // This is set by the config key spacecraft.sclkModulusOverride, and if that key is not set, then the SCLK fine modulus from the loaded SCLK kernel is used.
    private int tk_sclk_fine_tick_modulus;

    // The SCLK modulus used to read & write values from/into the SCLK kernel and SCLK-SCET files.
    private int sclk_kernel_fine_tick_modulus = -1;

    // the last SCLK kernel triplet as of runtime
    private CorrelationTriplet currentSclkKernelLatestTriplet;

    public TrendingApp(String... args) throws Exception {
        this.config = new TrendingConfig();
        this.config.validate();
        this.config.getTelemetrySource().applyConfiguration(this.config);

        this.appRunTime = OffsetDateTime.now(ZoneOffset.UTC);
        init();
    }

    private void init() throws Exception {
        logger.debug("Loading SPICE library and latest SCLK kernel");
        TimeConvert.loadSpiceLib();
        TimeConvert.loadSpiceKernels(config.getKernelsToLoad());
        TimeConvert.validateLoadedSclkKernels(config.getSpacecraftId());

        logger.info("SPICE kernels loaded:\n" + String.join("\n", TimeConvert.getLoadedKernelNames()));

        this.currentSclkKernelLatestTriplet = SclkKernel.read(config.getInputSclkKernelPath()).getLastTriplet();

        this.tk_sclk_fine_tick_modulus = config.getTkSclkFineTickModulus(true);
        this.sclk_kernel_fine_tick_modulus = TimeConvert.getSclkKernelTickRate(config.getNaifSpacecraftId());
    }

    private TrendingReportContext getNewContext(MmtcConfig.TrendingReportPeriodsConfig reportConfig) throws Exception {
        TrendingReportContext ctx = new TrendingReportContext(config, reportConfig, appRunTime);
        ctx.currentSclkKernel.set(SclkKernel.read(config.getInputSclkKernelPath()));
        ctx.currentSclkKernelDescription.set(config.getInputSclkKernelPath().getFileName().toString());
        ctx.currentSclkKernelLatestTriplet.set(ctx.currentSclkKernel.get().getLastTriplet());

        {
            final OffsetDateTime lastCorrelationScetUtc = TimeConvert.tdtToUtc(ctx.currentSclkKernelLatestTriplet.get().getTdt(), 6);
            ctx.currentSclkKernelLatestTripletAgeDays.set(
                    Duration.between(
                            lastCorrelationScetUtc,
                            ctx.appRunTime
                    ).toMinutes() / (60.0 * 24.0)
            );
        }

        return ctx;
    }

    public TrendingReportContext run() throws Exception {
        try {
            config.getTelemetrySource().connect();

            final MmtcConfig.TrendingReportPeriodsConfig trendingPeriodsConfig = config.getTrendingReportPeriods();
            final TrendingReportContext ctxForReport = getNewContext(trendingPeriodsConfig);
            calculateTrendingStats(ctxForReport);

            MmtcConfig.TrendingReportOutputFormatsConfig trendingOutputFormatsConfig = config.getTrendingReportOutputFormats(ctxForReport.appRunTime);

            for (MmtcConfig.TrendingReportOutputFormatConfig formatConfig : trendingOutputFormatsConfig.getAllEnabled()) {
                ReportWriter reportWriter = formatConfig.getWriter(ctxForReport);
                ctxForReport.reportOutputPathsByFormat.put(formatConfig.reportProductFormat, reportWriter.write());
            }

            return ctxForReport;

        } finally {
            config.getTelemetrySource().disconnect();
        }
    }

    private void calculateTrendingStats(TrendingReportContext ctx) throws Exception {
        if (ctx.reportConfig.isPastNDaysPeriodEnabled()) {
            ScetRange trendingRange = new ScetRange(ctx.appRunTime.minusDays(ctx.reportConfig.pastNDaysConfig.pastNum), ctx.appRunTime);

            logger.info(String.format("Calculating trending statistics over the past %d days", ctx.reportConfig.pastNDaysConfig.pastNum));
            ctx.statsPastNDays.set(
                    calculateTrendingStats(
                            String.format("Trend over past %d days", ctx.reportConfig.pastNDaysConfig.pastNum),
                            trendingRange,
                            ctx.reportConfig.pastNDaysConfig
                    )
            );
        }

        if (ctx.reportConfig.isPastNCorrelationsPeriodEnabled()) {
            // todo for missions configured with a sample set size > 1, this trending period will begin with the next sample set after that,
            // since the ERT query window won't include the full range of the sample set that yielded the original time correlation target
            // we'd need a reliable way to reconstruct the original sample set window for this
            final OffsetDateTime latestScetTimeFromKernel = TimeConvert.tdtToUtc(
                    ctx.currentSclkKernelLatestTriplet.get().getTdt(),
                    6
            );
            ScetRange trendingRange = new ScetRange(latestScetTimeFromKernel, ctx.appRunTime);

            final String lastCorrelation = TimeConvert.timeToIsoUtcString(latestScetTimeFromKernel, 0);
            logger.info(String.format("Calculating trending statistics since the last correlation on %s", lastCorrelation));
            ctx.statsSinceLastCorrelation.set(
                    calculateTrendingStats(
                            String.format("Trend since last %d correlation", ctx.reportConfig.pastNCorrelationsConfig.pastNum),
                            trendingRange,
                            ctx.reportConfig.pastNCorrelationsConfig
                    )
            );
        }
    }

    private TrendingStats calculateTrendingStats(String title, ScetRange overScetRange, MmtcConfig.TrendingReportPeriodPastNConfig trendingPastNConfig) throws Exception {
        final TrendingStats trendingStats = new TrendingStats();

        trendingStats.title.set(title);

        trendingStats.trendOverTimeRangeScetUtc.set(overScetRange);

        if (trendingPastNConfig.isTrendingMetricScetErrorEnabled()) {
            logger.info(String.format("Calculating SCET Error metrics over %s", overScetRange));
            trendingStats.scetErrorMetrics.set(calculateScetErrorMetrics(overScetRange));
        }

        if (trendingPastNConfig.isTrendingMetricTdtSErrorEnabled()) {
            logger.info(String.format("Calculating TDT(S) Error metrics over %s", overScetRange));
            trendingStats.tdtSErrorMetrics.set(calculateTdtSErrorMetrics(overScetRange));
        }

        return trendingStats;
    }

    private ErrorTrendingMetrics calculateScetErrorMetrics(ScetRange overScetRange) throws Exception {
        ErrorTrendingMetrics scetErrorMetrics = new ErrorTrendingMetrics();
        scetErrorMetrics.title.set("SCET Error");
        scetErrorMetrics.trendingPeriodId.set("SCET-Error-"+overScetRange.getRangeId());

        // SCET error should only be trended onward from the last SCLK kernel created, so set the min TDT appropriately
        final double minTdtGExclusive = currentSclkKernelLatestTriplet.getTdt();

        TelemetryRetriever tlmRetriever = new TelemetryRetriever(config);
        final List<FrameSampleAndMetrics> frameSamplesAndMetrics = tlmRetriever.retrieveAllFrameSamplesInRange(getTlmOptions(overScetRange, minTdtGExclusive));

        if (frameSamplesAndMetrics.isEmpty()) {
            logger.info("No telemetry found over the query period.  Skipping SCET Error statistic calculation.");
            scetErrorMetrics.sufficientDataForTrendingExists.set(false);
            return scetErrorMetrics;
        }

        if (frameSamplesAndMetrics.size() == 1) {
            logger.info("Only one time correlation point was found over the query period.  Skipping SCET Error statistic calculation.");
            scetErrorMetrics.sufficientDataForTrendingExists.set(false);
            return scetErrorMetrics;
        }

        scetErrorMetrics.sufficientDataForTrendingExists.set(true);

        final FrameSampleAndMetrics basisTlmPoint = frameSamplesAndMetrics.get(0);
        final FrameSampleAndMetrics latestTlmPoint = frameSamplesAndMetrics.get(frameSamplesAndMetrics.size() - 1);

        scetErrorMetrics.retrievedTelemetryTimeRange.set(new OffsetDateTimeRange(basisTlmPoint.metrics.scetUtc, latestTlmPoint.metrics.scetUtc));
        scetErrorMetrics.tlmForPlotting.set(
                frameSamplesAndMetrics.stream()
                        .map(fsm -> new TlmUtils.TlmPoint(fsm.metrics.scetUtc, new BigDecimal(fsm.metrics.getScetErrorMs())))
                        .collect(Collectors.toList())
        );

        logger.info("Basis TLM point for SCET Error calculation: " + basisTlmPoint);
        logger.info("Latest TLM point for SCET Error calculation: " + latestTlmPoint);

        scetErrorMetrics.priorScetUtcForErrorCalc.set(basisTlmPoint.metrics.scetUtc);
        scetErrorMetrics.priorErrorMs.set(new BigDecimal(basisTlmPoint.metrics.getScetErrorMs()));

        scetErrorMetrics.latestScetUtcForErrorCalc.set(latestTlmPoint.metrics.scetUtc);
        scetErrorMetrics.latestErrorMs.set(new BigDecimal(latestTlmPoint.metrics.getScetErrorMs()));

        TlmUtils.TrendingAndThresholdInformation scetErrorTrendingInfo = TlmUtils.estimateTimeAtWhichThresholdWillBeViolated(
                new TlmUtils.TlmPoint(
                        scetErrorMetrics.priorScetUtcForErrorCalc.get(),
                        scetErrorMetrics.priorErrorMs.get()
                ),
                new TlmUtils.TlmPoint(
                        scetErrorMetrics.latestScetUtcForErrorCalc.get(),
                        scetErrorMetrics.latestErrorMs.get()
                ),
                config.getTrendingScetErrorThresholdMs()
        );

        scetErrorMetrics.errorThresholdMs.set(new BigDecimal(config.getTrendingScetErrorThresholdMs()));
        scetErrorMetrics.valChangeRateMsPerDay.set(scetErrorTrendingInfo.valChangeRatePerDay);
        scetErrorMetrics.thresholdAlreadyViolated.set(scetErrorTrendingInfo.thresholdAlreadyViolated);
        scetErrorMetrics.estimatedScetWhenErrorThresholdWillBeReached.set(scetErrorTrendingInfo.expectedScetAtWhichThresholdWillBeViolated);
        scetErrorMetrics.numDaysUntilErrorThresholdWillBeReached.set(calcNumDaysUntil(scetErrorTrendingInfo.expectedScetAtWhichThresholdWillBeViolated));

        return scetErrorMetrics;
    }

    private ErrorTrendingMetrics calculateTdtSErrorMetrics(ScetRange scetRange) throws TimeConvertException, IOException {
        ErrorTrendingMetrics tdtSErrorMetrics = new ErrorTrendingMetrics();
        tdtSErrorMetrics.title.set("TDT(S) Error");
        tdtSErrorMetrics.trendingPeriodId.set("TDTS-Error-"+scetRange.getRangeId());

        List<TelemetrySource.GncSclkAndTdtSMeasurement> gncTelemetryPoints = config.getTelemetrySource().getGncTelemetryPoints(scetRange);

        if (gncTelemetryPoints.isEmpty()) {
            logger.info("No telemetry found over the query period.  Skipping TDT(S) Error statistic calculation.");
            tdtSErrorMetrics.sufficientDataForTrendingExists.set(false);
            return tdtSErrorMetrics;
        }

        if (gncTelemetryPoints.size() == 1) {
            logger.info("Only one telemetry point was found over the query period.  Skipping TDT(S) Error statistic calculation.");
            tdtSErrorMetrics.sufficientDataForTrendingExists.set(false);
            return tdtSErrorMetrics;
        }

        tdtSErrorMetrics.sufficientDataForTrendingExists.set(true);

        final TelemetrySource.GncSclkAndTdtSMeasurement basisTlmPoint = gncTelemetryPoints.get(0);
        final TelemetrySource.GncSclkAndTdtSMeasurement latestTlmPoint = gncTelemetryPoints.get(gncTelemetryPoints.size() - 1);

        tdtSErrorMetrics.retrievedTelemetryTimeRange.set(new OffsetDateTimeRange(basisTlmPoint.getCommonScetForGncSclkAndTdtS(), latestTlmPoint.getCommonScetForGncSclkAndTdtS()));
        tdtSErrorMetrics.tlmForPlotting.set(
                gncTelemetryPoints.stream()
                        .map(gncTlmPoint -> {
                            try {
                                return new TlmUtils.TlmPoint(
                                        gncTlmPoint.getCommonScetForGncSclkAndTdtS(),
                                        new BigDecimal(
                                                TimeCorrelationAncillaryOperations.computeTdtSErrorMs(
                                                        gncTlmPoint.toGncParms(),
                                                        TimeConvert.encSclkToSclk(config.getNaifSpacecraftId(), sclk_kernel_fine_tick_modulus, currentSclkKernelLatestTriplet.encSclk.doubleValue()),
                                                        currentSclkKernelLatestTriplet.getTdt(),
                                                        currentSclkKernelLatestTriplet.getClkChgRate()
                                                )
                                        )
                                );
                            } catch (TimeConvertException e) {
                                throw new RuntimeException(e);
                            }
                        })
                        .collect(Collectors.toList())
        );

        logger.info("Basis TLM point for TDT(S) Error calculation: " + basisTlmPoint);
        logger.info("Latest TLM point for TDT(S) Error calculation: " + latestTlmPoint);

        tdtSErrorMetrics.priorScetUtcForErrorCalc.set(basisTlmPoint.getCommonScetForGncSclkAndTdtS());
        tdtSErrorMetrics.priorErrorMs.set(
                new BigDecimal(
                    TimeCorrelationAncillaryOperations.computeTdtSErrorMs(
                            basisTlmPoint.toGncParms(),
                            TimeConvert.encSclkToSclk(config.getNaifSpacecraftId(), sclk_kernel_fine_tick_modulus, currentSclkKernelLatestTriplet.encSclk.doubleValue()),
                            currentSclkKernelLatestTriplet.getTdt(),
                            currentSclkKernelLatestTriplet.getClkChgRate()
                    )
                )
        );

        tdtSErrorMetrics.latestScetUtcForErrorCalc.set(latestTlmPoint.getCommonScetForGncSclkAndTdtS());
        tdtSErrorMetrics.latestErrorMs.set(
                new BigDecimal(
                    TimeCorrelationAncillaryOperations.computeTdtSErrorMs(
                            latestTlmPoint.toGncParms(),
                            TimeConvert.encSclkToSclk(config.getNaifSpacecraftId(), sclk_kernel_fine_tick_modulus, currentSclkKernelLatestTriplet.encSclk.doubleValue()),
                            currentSclkKernelLatestTriplet.getTdt(),
                            currentSclkKernelLatestTriplet.getClkChgRate()
                    )
                )
        );

        TlmUtils.TrendingAndThresholdInformation tdtSErrorTrendingInfo = TlmUtils.estimateTimeAtWhichThresholdWillBeViolated(
                new TlmUtils.TlmPoint(
                        tdtSErrorMetrics.priorScetUtcForErrorCalc.get(),
                        tdtSErrorMetrics.priorErrorMs.get()
                ),
                new TlmUtils.TlmPoint(
                        tdtSErrorMetrics.latestScetUtcForErrorCalc.get(),
                        tdtSErrorMetrics.latestErrorMs.get()
                ),
                config.getTrendingTdtSErrorThresholdMs()
        );

        tdtSErrorMetrics.errorThresholdMs.set(new BigDecimal(config.getTrendingTdtSErrorThresholdMs()));
        tdtSErrorMetrics.valChangeRateMsPerDay.set(tdtSErrorTrendingInfo.valChangeRatePerDay);
        tdtSErrorMetrics.thresholdAlreadyViolated.set(tdtSErrorTrendingInfo.thresholdAlreadyViolated);
        tdtSErrorMetrics.estimatedScetWhenErrorThresholdWillBeReached.set(tdtSErrorTrendingInfo.expectedScetAtWhichThresholdWillBeViolated);
        tdtSErrorMetrics.numDaysUntilErrorThresholdWillBeReached.set(calcNumDaysUntil(tdtSErrorTrendingInfo.expectedScetAtWhichThresholdWillBeViolated));

        return tdtSErrorMetrics;
    }

    private Optional<BigDecimal> calcNumDaysUntil(Optional<OffsetDateTime> maybeTime) {
        if (! maybeTime.isPresent()) {
            return Optional.empty();
        }

        return Optional.of(TimeConvert.numDaysBetween(appRunTime, maybeTime.get()));
    }

    private TelemetrySelectionAndAdjustmentOptions getTlmOptions(ScetRange scetRange, Double minTdtExclusive) throws TimeConvertException {
        final ErtRange ertRange = new ErtRange(
                Owlt.scetToCenterOfEarthErt(scetRange.getStart(), config.getNaifSpacecraftId()),
                Owlt.scetToCenterOfEarthErt(scetRange.getStop(), config.getNaifSpacecraftId())
        );

        return new TelemetrySelectionAndAdjustmentOptions() {
            @Override
            public TimeCorrelationRunConfig.TargetSampleInputErtMode getTargetSampleInputErtMode() {
                return TimeCorrelationRunConfig.TargetSampleInputErtMode.RANGE;
            }

            @Override
            public Optional<OffsetDateTimeRange> getResolvedTargetSampleErtRange() {
                return Optional.of(ertRange);
            }

            @Override
            public TargetSampleRangeErtSeekOrder getTargetSampleRangeErtSeekOrder() {
                return TargetSampleRangeErtSeekOrder.DESCENDING;
            }

            @Override
            public Optional<OffsetDateTime> getResolvedTargetSampleExactErt() {
                return Optional.empty();
            }

            @Override
            public Optional<Double> getMinTdtGExclusive() {
                return Optional.of(minTdtExclusive);
            }

            @Override
            public boolean isTestMode() {
                return false;
            }

            @Override
            public double getTestModeOwlt() {
                return 0;
            }
        };
    }
}
